*** ../squashfs/Makefile	2018-07-09 15:43:00.000000000 -0700
--- squashfs/Makefile	2018-07-09 15:01:51.000000000 -0700
***************
*** 15,17 ****
--- 15,18 ----
  squashfs-$(CONFIG_SQUASHFS_LZO) += lzo_wrapper.o
  squashfs-$(CONFIG_SQUASHFS_XZ) += xz_wrapper.o
  squashfs-$(CONFIG_SQUASHFS_ZLIB) += zlib_wrapper.o
+ squashfs-$(CONFIG_SQUASHFS_SSQ) += ssq.o
